import sharp from 'sharp';

interface WinnerImageData {
  username: string;
  avatar?: string;
  comment?: string;
  prize?: string;
}

/**
 * Generate a beautiful JPEG winner image for Instagram stories (1080x1920)
 * Returns JPEG buffer optimized for Instagram
 */
export async function generateWinnerImageJPEG(data: WinnerImageData): Promise<Buffer> {
  const width = 1080;
  const height = 1920;

  // Create a beautiful gradient background using sharp
  const gradientSvg = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="0" y2="${height}">
          <stop offset="0%" stop-color="#E1306C"/>
          <stop offset="50%" stop-color="#C13584"/>
          <stop offset="100%" stop-color="#833AB4"/>
        </linearGradient>
      </defs>
      <rect width="${width}" height="${height}" fill="url(#bg)"/>
    </svg>
  `;

  let background = await sharp(Buffer.from(gradientSvg))
    .resize(width, height)
    .jpeg({ quality: 95 })
    .toBuffer();

  // Create text overlays using SVG
  const avatarSize = 320;
  const avatarY = 400;
  const avatarCenterX = width / 2;
  const avatarCenterY = avatarY + avatarSize / 2;

  // Word wrap comment
  const commentText = data.comment || '';
  const words = commentText.split(' ');
  const maxCharsPerLine = 30;
  const commentLines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + ' ' + word).length > maxCharsPerLine && currentLine) {
      commentLines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = currentLine ? currentLine + ' ' + word : word;
    }
  }
  if (currentLine) {
    commentLines.push(currentLine);
  }

  // Create text SVG overlay
  const textOverlay = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      <!-- Decorative circles -->
      <circle cx="${width * 0.15}" cy="${height * 0.2}" r="80" fill="white" opacity="0.1"/>
      <circle cx="${width * 0.85}" cy="${height * 0.8}" r="120" fill="white" opacity="0.1"/>
      
      <!-- Title with shadow -->
      <text x="${width / 2}" y="280" font-family="Arial, sans-serif" font-size="88" font-weight="900" fill="#FFFFFF" text-anchor="middle" opacity="0.95">
        <tspan x="${width / 2}" dy="0">🎉 YOU WON! 🎉</tspan>
      </text>
      
      <!-- Username with larger, bolder font -->
      <text x="${width / 2}" y="${avatarY + avatarSize + 140}" font-family="Arial, sans-serif" font-size="76" font-weight="900" fill="#FFFFFF" text-anchor="middle" letter-spacing="2">
        @${data.username}
      </text>
      
      <!-- Comment in a styled box -->
      ${commentLines.length > 0 ? `
        <rect x="${width * 0.1}" y="${avatarY + avatarSize + 220}" width="${width * 0.8}" height="${commentLines.length * 70 + 40}" rx="20" fill="white" opacity="0.15"/>
        ${commentLines.map((line, i) => `
          <text x="${width / 2}" y="${avatarY + avatarSize + 260 + (i * 70)}" font-family="Arial, sans-serif" font-size="52" font-weight="600" fill="#FFFFFF" text-anchor="middle">
            "${line}"
          </text>
        `).join('')}
      ` : ''}
      
      <!-- Branding at bottom -->
      <text x="${width / 2}" y="${height - 80}" font-family="Arial, sans-serif" font-size="32" fill="#FFFFFF" text-anchor="middle" opacity="0.8">
        Generated by giveaway-engine.com
      </text>
    </svg>
  `;

  const textBuffer = Buffer.from(textOverlay);

  let avatarBuffer: Buffer | null = null;
  if (data.avatar) {
    try {
      const avatarResponse = await fetch(data.avatar);
      if (avatarResponse.ok) {
        const avatarArrayBuffer = await avatarResponse.arrayBuffer();
        avatarBuffer = await sharp(Buffer.from(avatarArrayBuffer))
          .resize(avatarSize, avatarSize, {
            fit: 'cover',
            position: 'center',
            kernel: sharp.kernel.lanczos3, // High quality resize algorithm
          })
          .composite([{
            input: Buffer.from(`
              <svg width="${avatarSize}" height="${avatarSize}">
                <circle cx="${avatarSize / 2}" cy="${avatarSize / 2}" r="${avatarSize / 2}" fill="none" stroke="white" stroke-width="8"/>
              </svg>
            `),
            top: 0,
            left: 0,
          }])
          .png({ quality: 100, compressionLevel: 6 })
          .toBuffer();
      }
    } catch (e) {
      console.error('Failed to load avatar:', e);
    }
  }

  // Create avatar placeholder if no avatar
  if (!avatarBuffer) {
    const initial = data.username.charAt(0).toUpperCase();
    const avatarSvg = `
      <svg width="${avatarSize}" height="${avatarSize}" xmlns="http://www.w3.org/2000/svg">
        <circle cx="${avatarSize / 2}" cy="${avatarSize / 2}" r="${avatarSize / 2}" fill="#FFFFFF"/>
        <text x="${avatarSize / 2}" y="${avatarSize / 2 + 50}" font-family="Arial, sans-serif" font-size="140" font-weight="900" fill="#E1306C" text-anchor="middle">${initial}</text>
        <circle cx="${avatarSize / 2}" cy="${avatarSize / 2}" r="${avatarSize / 2}" fill="none" stroke="#E1306C" stroke-width="8"/>
      </svg>
    `;
    avatarBuffer = await sharp(Buffer.from(avatarSvg)).png().toBuffer();
  }

  // Composite everything together
  const composites: any[] = [
    {
      input: textBuffer,
      top: 0,
      left: 0,
    },
    {
      input: avatarBuffer,
      top: avatarY,
      left: (width - avatarSize) / 2,
    },
  ];

  const finalImage = await sharp(background)
    .composite(composites)
    .jpeg({
      quality: 95,
      mozjpeg: true,
      progressive: true,
    })
    .toBuffer();

  return finalImage;
}
